### ISSUE TITLE
Error from Matrix

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/thingengine-core#13]
sendEvent of type org.thingpedia.v1.message in !xEFtILHNVrIaRQuLxs:matrix.org with txnId m1526001529794.2
Error sending event Error: Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.
at Crypto.encryptEvent (/opt/thingengine/node_modules/matrix-js-sdk/lib/crypto/index.js:830:15)
at _encryptEventIfNeeded (/opt/thingengine/node_modules/matrix-js-sdk/lib/client.js:1289:27)
at /opt/thingengine/node_modules/matrix-js-sdk/lib/client.js:1201:33
at tryCatcher (/opt/thingengine/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/opt/thingengine/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/opt/thingengine/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromiseCtx (/opt/thingengine/node_modules/bluebird/js/release/promise.js:606:10)
at Async._drainQueue (/opt/thingengine/node_modules/bluebird/js/release/async.js:138:12)
at Async._drainQueues (/opt/thingengine/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/opt/thingengine/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:794:20)
at tryOnImmediate (timers.js:752:5)
at processImmediate [as _immediateCallback] (timers.js:729:5)
setting pendingEvent status to not_sent in !xEFtILHNVrIaRQuLxs:matrix.org
Ignored error from permission control request: undefined: Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.

**Comment by gcampax** [comment]
This was an encryption related bug, and encryption is disabled now. We'll revisit this when encryption is enabled again.
